version: '3.6'
services:
  mongo:
    container_name: course-project-mongo
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - course-project
    ports:
      - "27017:27017"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-cfg
        target: /data/configdb
  web:
    build: web/
    container_name: course-project-web
    command: bash -c "npm run dev"
    ports:
      - "3000:3000"
  api:
    build: api/
    depends_on:
      -  mongo
    command: bash -c "npm start"
    networks:
      - course-project
    ports:
      - "3001:3001"
    links:
      - mongo
    container_name: course-project-api

networks:
  course-project:
    name: course-project-network

volumes:
  mongodb:
  mongodb-cfg:
